name: Build c2addon

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Install zip
        uses: actions/checkout@v1
      - name: 🔧 Packaging c2addon
        run: zip -r c2airconsole.c2addon.test plugin
