name: Build c2addon

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Install zip
        uses: montudor/action-zip@v1
      - name: 🔧 Packaging c2addon
        run: zip -qq -r c2airconsole.c2addon.test files info.xml
        working-directory: plugin
